# Photobooth — Ansible Inventory
# ================================
# Pas het IP/hostname aan naar jouw Pi.
# SSH key moet al gekopieerd zijn:
#   ssh-copy-id pi@photobooth.local

[photobooth]
booth  ansible_host=192.168.0.125  ansible_user=photobooth

[photobooth:vars]
ansible_python_interpreter=/usr/bin/python3
app_dir=/opt/photobooth
venv_dir=/opt/photobooth/.venv
booth_user=photobooth
booth_group=photobooth
